const farmLifeActionTypes = {
  SET_SAVE_ID: "[FARM_LIFE] SET_SAVE_ID",
  SET_SAVES: "[FARM_LIFE] SET_SAVES",
  SET_TILES: "[FARM_LIFE] SET_TILES",
  SET_INVENTORY: "[FARM_LIFE] SET_INVENTORY",
  SET_CURRENCY: "[FARM_LIFE] SET_CURRENCY",
  SET_PLANTS: "[FARM_LIFE] SET_PLANTS",
};

export default farmLifeActionTypes;
